// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA02RoCyBkUtxJfk2W-0f2PGjbCUAMZmqw',
    appId: '1:1058837392538:web:e64694d105b94a063f4323',
    messagingSenderId: '1058837392538',
    projectId: 'expert-car',
    authDomain: 'expert-car.firebaseapp.com',
    storageBucket: 'expert-car.firebasestorage.app',
    measurementId: 'G-8KX8H3MKZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGWGi6-VOFw1VfQtNfb_oZm2UBVvWpmu4',
    appId: '1:1058837392538:android:675c50894a3002993f4323',
    messagingSenderId: '1058837392538',
    projectId: 'expert-car',
    storageBucket: 'expert-car.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM_yWPonufymesnyFtg3Pph-auogU2TZ4',
    appId: '1:1058837392538:ios:f45498f3a60ba0853f4323',
    messagingSenderId: '1058837392538',
    projectId: 'expert-car',
    storageBucket: 'expert-car.firebasestorage.app',
    iosBundleId: 'com.example.expertCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM_yWPonufymesnyFtg3Pph-auogU2TZ4',
    appId: '1:1058837392538:ios:f45498f3a60ba0853f4323',
    messagingSenderId: '1058837392538',
    projectId: 'expert-car',
    storageBucket: 'expert-car.firebasestorage.app',
    iosBundleId: 'com.example.expertCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA02RoCyBkUtxJfk2W-0f2PGjbCUAMZmqw',
    appId: '1:1058837392538:web:46cadcf0688ae4983f4323',
    messagingSenderId: '1058837392538',
    projectId: 'expert-car',
    authDomain: 'expert-car.firebaseapp.com',
    storageBucket: 'expert-car.firebasestorage.app',
    measurementId: 'G-6ZH7C2DDD8',
  );

}